/*
 Rocrail - Model Railroad Software

 Copyright (C) 2002-2015 Rob Versluis, Rocrail.net

 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 as published by the Free Software Foundation; either version 2
 of the License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

#ifndef __tracedlg__
#define __tracedlg__

/**
@file
Subclass of TraceDlgGen, which is generated by wxFormBuilder.
*/

#include "tracedlggen.h"
#include "rocs/public/node.h"

//// end generated include

/** Implementing TraceDlgGen */
class TraceDlg : public TraceDlgGen
{
  char* m_TraceFile;
  void initLabels();
  char* m_Text;

	protected:
		// Handlers for TraceDlgGen events.
		void onOpen( wxCommandEvent& event );
		void onHelp( wxCommandEvent& event );
		void onOK( wxCommandEvent& event );
    void onObjectType( wxCommandEvent& event );
    void onSearch( wxCommandEvent& event );
    void onClose( wxCloseEvent& event );
    void addLine(const char* text);
    void onLevel( wxCommandEvent& event );

	public:
		/** Constructor */
		TraceDlg( wxWindow* parent );
    ~TraceDlg();
    void traceEvent(iONode node);
	//// end generated class members
	
};

#endif // __tracedlg__
